services:
  # Minecraft Server
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile.minecraft
    container_name: minecraft-server
    restart: no
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "true"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "2G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: 0808
      RCON_PORT: 25575
    volumes:
      - /home/redeyes/Documents/mc-data:/data
    networks:
      - mc-network

  # Discord Bot (Dev)
  bot-dev:
    image: node:alpine
    container_name: mc-bot-dev
    command: sh -c "tail -f /dev/null"
    restart: unless-stopped
    ports:
      - "127.0.0.1:9009:3000"
    env_file:
      - ./bot/.env
    volumes:
      - ./bot:/app
      - /home/redeyes/Documents/mc-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    networks:
      - mc-network
    depends_on:
      - minecraft

networks:
  mc-network:
    driver: bridge
