package handlers








































































































































}	})		Message: "Server is stopping",		Success: true,	return c.JSON(models.SuccessResponse{	})		Payload: fiber.Map{"status": "stopped"},		Type:    "server_stopped",	h.hub.Broadcast(models.WSMessage{	// Broadcast to WebSocket clients	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "stop_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err := h.dockerService.Stop(); err != nil {	// Stop server	}		})			Code:    fiber.StatusBadRequest,			Message: "Server is not running",			Error:   "not_running",		return c.Status(fiber.StatusBadRequest).JSON(models.ErrorResponse{	if !isRunning {	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "status_check_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err != nil {	isRunning, err := h.dockerService.IsRunning()	// Check if runningfunc (h *ServerHandler) Stop(c *fiber.Ctx) error {// Stop stops the Minecraft server}	})		Message: "Server is starting",		Success: true,	return c.JSON(models.SuccessResponse{	})		Payload: fiber.Map{"status": "starting"},		Type:    "server_started",	h.hub.Broadcast(models.WSMessage{	// Broadcast to WebSocket clients	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "start_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err := h.dockerService.Start(); err != nil {	// Start server	}		})			Code:    fiber.StatusBadRequest,			Message: "Server is already running",			Error:   "already_running",		return c.Status(fiber.StatusBadRequest).JSON(models.ErrorResponse{	if isRunning {	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "status_check_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err != nil {	isRunning, err := h.dockerService.IsRunning()	// Check if already runningfunc (h *ServerHandler) Start(c *fiber.Ctx) error {// Start starts the Minecraft server}	})		"count":   len(players),		"players": players,	return c.JSON(fiber.Map{	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "players_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err != nil {	players, err := h.minecraftService.GetPlayers()func (h *ServerHandler) GetPlayers(c *fiber.Ctx) error {// GetPlayers returns the list of online players}	return c.JSON(status)	}		})			Code:    fiber.StatusInternalServerError,			Message: err.Error(),			Error:   "status_error",		return c.Status(fiber.StatusInternalServerError).JSON(models.ErrorResponse{	if err != nil {	status, err := h.minecraftService.GetStatus()func (h *ServerHandler) GetStatus(c *fiber.Ctx) error {// GetStatus returns the current server status}	}		hub:              hub,		dockerService:    docker,		minecraftService: mc,	return &ServerHandler{func NewServerHandler(mc *services.MinecraftService, docker *services.DockerService, hub *ws.Hub) *ServerHandler {}	hub              *ws.Hub	dockerService    *services.DockerService	minecraftService *services.MinecraftServicetype ServerHandler struct {)	"github.com/gofiber/fiber/v2"	"mc-bot-server/internal/ws"	"mc-bot-server/internal/services"	"mc-bot-server/internal/models"import (package handlers